apiVersion: apps/v1
kind: Deployment
metadata:
  name: jbrangwynpipelinetest 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jbrangwynpipelinetest
  template:
    metadata:
      labels:
        app: jbrangwynpipelinetest
    spec:
      containers:
        - name: jbrangwynpipelinetest 
          image: jbkb8cr.azurecr.io/jbrangwynpipelinetest
          ports:
          - containerPort: 8080
