apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: jbrangwynpipelinetest
spec:
  selector:
    matchLabels:
      app: jbrangwynpipelinetest
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: jbrangwynpipelinetest
    spec:
      containers:
      - name: jbrangwynpipelinetest
        image: jbkb8cr.azurecr.io/jbrangwynpipelinetest
        ports:
        - containerPort: 8080
